sudo: false
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
jdk: oraclejdk8
language: scala
before_install:
  - git submodule update --init --recursive
install:
  - '[ ! -d ~/bin ] && mkdir ~/bin || true'
  - ./sbt update

# we run extension tests separately because some extensions leak resources which
# are only claimed on process exit
script:
  - ./sbt all
  - ./sbt depend
  - ./sbt headless/depend
  - ./sbt netlogo/test:fast
  - ./sbt parserJS/test
  - ./sbt nogen netlogo/test:fast
  - ./sbt threed netlogo/test:fast
  - ./sbt headless/test:fast
  - ./sbt netlogo/test:medium
  - ./sbt nogen netlogo/test:medium
  - ./sbt headless/test:medium
  - ./sbt nogen headless/test:medium
  - ./sbt netlogo/test:slow
  - ./sbt threed netlogo/test:slow
  - ./sbt netlogo/test:extensionTests
